---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install plugin dir
  file:
    path: "{{ maas_plugin_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Install MAAS Plugins
  synchronize:
    src: "{{ maas_source_plugin_dir }}"
    dest: "{{ maas_plugin_dir }}"
    delete: yes

- name: Drop in wrapper script to run maas plugins in venv
  template:
    src: "run_plugin_in_venv.sh.j2"
    dest: "{{maas_plugin_dir}}run_plugin_in_venv.sh"
    owner: "root"
    group: "root"
    mode: "0755"
  when: maas_venv_enabled

- name: List plugin files to chmod
  find:
    path: "{{ maas_plugin_dir }}"
    patterns: "*.py"
  register: plugin_files

- name: Chmod listed plugin files
  file:
    path: "{{ item.path }}"
    mode: "0755"
  with_items: "{{ plugin_files.files|default({}) }}"
  when: plugin_files.files|length > 0

- name: Ensure raspace-monitoring-agent config directory exists
  file:
    name: /etc/rackspace-monitoring-agent.conf.d
    state: directory
    group: root
    owner: root
  tags:
    - rackspace-monitoring-agent-setup

