---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create openrc file
  template:
    src: "openrc"
    dest: "/root/openrc-maas"
    owner: "root"
    group: "root"
    mode: "0600"

# TODO (mattt): Modify openstack_openrc role to allow us to pass in arbitrary
#               details.  This is a refactor which will need to wait until a
#               later date.
- name: Create keystone user for monitoring
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ maas_keystone_user }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    password: "{{ maas_keystone_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"

- name: Add monitoring keystone user to admin role
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ maas_keystone_user }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    role_name: "admin"
    insecure: "{{ keystone_service_adminuri_insecure }}"
