---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Merge regular expressions for excluded checks/alarms into a single
# regular expression string. If the lists are empty, use '^$' as the regular
# expression since it does not match anything.
- name: Gather regular expressions for excluded checks and alarms
  set_fact:
    maas_excluded_checks_regex: "{{ (maas_excluded_checks | length > 0) | ternary('('+maas_excluded_checks | join(')|(')+')', '^$') }}"
    maas_excluded_alarms_regex: "{{ (maas_excluded_alarms | length > 0) | ternary('('+maas_excluded_alarms | join(')|(')+')', '^$') }}"
  tags:
    - always

- include: maas_pre_install.yml
  tags:
    - maas-config

- include: maas_host_setup.yml
  when:
    - inventory_hostname in groups['hosts']
  tags:
    - maas-install

- include: maas_infra.yml
  tags:
    - maas-checks
    - maas-checks-infra

- include: maas_host_monitoring.yml
  when:
    - inventory_hostname in groups['hosts']
  tags:
    - maas-checks
    - maas-checks-hosts

- include: maas_openstack.yml
  tags:
    - maas-checks
    - maas-checks-openstack

- include: maas_ceph.yml
  when:
    - "'ceph_all' in groups"
    - inventory_hostname in groups['ceph_all']
  tags:
    - maas-checks
    - maas-checks-ceph

- include: maas_checks.yml
  tags:
    - maas-checks
    - maas-checks-extra

- include: maas_restart_raxmon.yml
  when:
    - inventory_hostname in groups['hosts']
  tags:
    - maas-config
