---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: rsyslog_all
  gather_facts: true
  become: true
  tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Include OSP vars
      include_vars: vars/maas-osp.yml
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

    - name: Set the current group
      set_fact:
        maas_current_group: rsyslog_all

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  tags:
    - always


- name: Install checks for infra rsyslog
  hosts: rsyslog_all
  gather_facts: true
  user: "{{ ansible_user | default('root') }}"
  become: true
  pre_tasks:
    - name: Include OSP vars
      include_vars: vars/maas-osp.yml
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

  tasks:
    - name: Install rsyslog check
      template:
        src: "templates/rax-maas/rsyslogd_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/rsyslogd_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - "vars/maas-{{ ansible_distribution | lower }}.yml"

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-infra-rsyslog
