---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Note: This is very limited, e.g. no pollers,etc. + assumes maas is setup
# by the puppet scripts

# To install call (in undercloud: . stackrc before):
# ansible-playbook -i /usr/bin/tripleo-ansible-inventory -e "director_openrc=/home/stack/lab1rc"  \
# -e "external_lb_vip_address=172.26.232.10" -e "internal_vip_address=172.26.236.62" \
# -e "maas_plugin_dir=/usr/lib/rackspace-monitoring-agent/plugins2" site-osp.yml

# Note: You will need to restart the maas agent manually for the changes this script introduces
#       to take effect.

- name: Prepare MaaS
  hosts: "Controller"
  user: "heat-admin"
  become: yes
  gather_facts: "{{ gather_facts | default(true) }}"
  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"

    - name: Get pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python /tmp/get-pip.py
      args:
        creates: "/usr/bin/pip"

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2

    - name: Install Linux packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
       - git
       - curl
       - autoconf
       - gcc
       - gcc-c++
       - nc
       - python2
       - python2-devel
       - openssl-devel
       - libffi-devel
       - libselinux-python

    - name: Install pip packages to venv
      pip:
        name: "{{ maas_pip_packages  }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
    - name: Create maas dirs # triple check if that's the right dir
      file:
        path: "{{ item }}"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"
      with_items:
        - "/etc/rackspace-monitoring-agent.conf.d/"
        - "{{ maas_plugin_dir }}"

    - name: Install MAAS Plugins
      synchronize:
        src: "files/rax-maas/plugins/"
        dest: "{{ maas_plugin_dir }}"
        recursive: yes
        times: yes
        rsync_opts:
          - "--no-motd"


    - name: Drop in wrapper script to run maas plugins in venv
      template: # todo: make more configurable for RPC-R
        src: "templates/rax-maas/run_plugin_in_venv.sh.j2"
        dest: "/usr/lib/rackspace-monitoring-agent/plugins/run_plugin_in_venv.sh"
        owner: "root"
        group: "root"
        mode: "0755"

  vars_files:
    - vars/main.yml
    - vars/maas-agent.yml
    - vars/maas-osp.yml



- include: maas-openstack-octavia.yml
  tags:
    - maas
  vars:
    octavia_var_files: 'vars/maas-osp.yml'
    octavia_hosts_all: 'Controller'
    octavia_ansible_user: 'heat-admin'
    octavia_ansible_become: yes


- include: maas-managed-k8.yml
  tags:
    - maas
  vars:
    mk8s_var_file: 'vars/maas-osp.yml'

- include: maas-openstack-designate.yml
  tags:
    - maas
  vars:
    designate_var_files: 'vars/maas-osp.yml'